### ISSUE TITLE
centralisation of extensions/pragmas

### ISSUE THREAD

**Issue by mwotton** [jaspervdj/stylish-haskell#138]
I use a few tools like stylish-haskell, hlint etc - all of them need to know what extensions to use. While I could put them all in every file, i generally have a list of extensions i want to use everywhere in the project, and would prefer to centralise them _somewhere_. is there some way of pulling them from .ghci, the cabal file, or stack.yaml? i really don't care which, but duplicating them for every tool is a real pain.

**Comment by jaspervdj** [comment]
Yes, `cabal` would be the best place to store these.  Unfortunately it is not simple to parse cabal files.  That is why I usually put the required extensions at the top of every file -- that should be understood by every tool.

**Comment by mwotton** [comment]
yes, that's an option, but it becomes very unwieldy when you have many files and many extensions.

**Comment by mwotton** [comment]
would you accept a PR that added a yaml file with a list of extensions, or a prelude to be silently prepended to each file?

**Comment by jaspervdj** [comment]
I'd rather not add an additional file, that's just creating another standard.  Would it be possible to parse it from the cabal file, either using the Cabal library, or just a simple custom parser that recognizes extension names.

**Comment by keremispirli** [comment]
With the introduction of [hpack](https://github.com/sol/hpack), such extensions can be listed under `default-extensions` in  `package.yaml` file. 

From the ReadMe file:

>  Both `cabal2nix` and `stack` support `package.yaml` natively.

But unfortunately I could not get it working with `stylish-haskell` as of 0.9.0.2.

I use VS Code with [stylish-haskell](https://marketplace.visualstudio.com/items?itemName=vigoo.stylish-haskell) addon. I had to disable it since migrating to `hpack` because I get errors like:
`Language.Haskell.Stylish.Parse.parseModule: could not parse (...)\src\API.hs: ParseFailed (SrcLoc "<unknown>.hs" 34 1) "TypeOperators language extension is not enabled. Please add {-# LANGUAGE TypeOperators #-} pragma at the top of your module."`

Is this because stylish-haskell doesn't support it yet or the add-on fails to pass something to stylish-haskell?

**Comment by matt-snider** [comment]
@keremispirli  I also use hpack and the VS Code stylish-haskell addon. I get the exact same errors. Did you find any way of getting stylish-haskell to consider the package.yaml file?

**Comment by keremispirli** [comment]
@matt-snider Unfortunately, no. Not even with 0.9.2.0 update. I add the extension lines during development and delete them before delivery, which is not fun. If you have a less boring idea please share.

**Comment by safareli** [comment]
Is there any updates on this? can someone familiar with the codebase outline what needs to be done so it's easy for someone to pick this up and fix it.

**Comment by jaspervdj** [comment]
Summarizing the current situation, there are two places you can currently add extensions that `stylish-haskell` understands:
- Add the top of each file
- In the `language_extensions` array in your project-specific or global `stylish-haskell` configuration

I don't have time to work on this myself but I would happily review PRs that extract extensions from `package.yaml` or `Cabal` files.  This code would go into `Language.Haskell.Stylish.Config.loadConfig`, and it would simply add the list of extensions to the currently loaded list.

**Comment by geo2a** [comment]
I have implemented a fix that gathers all the availible `default-extension` fields in the project's `.cabal` file and supplies `stylish-haskell` with those (see PR #241). I would be happy to get feedback on it, especially from non-Linux and non-Emacs users!

**Comment by jaspervdj** [comment]
Fixed (after three years!) by @geo2a and available in `stylish-haskell-0.9.4.0`.
