### ISSUE TITLE
Switch to ghc-lib?

### ISSUE THREAD

**Issue by maksbotan** [jaspervdj/stylish-haskell#263]
Hello,

First of all, thanks for this nice tool!

As you know, https://github.com/haskell-suite/haskell-src-exts is on life support and is always lagging in terms of new language features.

Recently, hlint switched to ghc-lib [1] [2] as their parsing backend: https://neilmitchell.blogspot.com/2019/06/hlints-path-to-ghc-parser.html

Are there any plans to make this transition here as well?

[1] https://neilmitchell.blogspot.com/2019/02/announcing-ghc-lib.html
[2] https://github.com/digital-asset/ghc-lib

**Comment by jaspervdj** [comment]
Hi @maksbotan, I would also like to make this switch.  I have tentative plans to try and turn this into a GSoC project so a student can perhaps take this on.

**Comment by maksbotan** [comment]
Hi @jaspervdj!
Thanks for the response. I hope this will succeed.

**Comment by Matts966** [comment]
@jaspervdj 
Hi, I am an undergrad student of the University of Tokyo Japan, very interested in this issue for GSoC 2020.

I am refering to the issue of hlint and thinking of a plan for this issue now. Here is some steps towards the goal.
- [ ] Add ghc-lib-parser as a dependency
- [ ] Parse all files with both ghc-lib-parser and current parser
- [ ] Make it a parse error if you can't parse with ghc-lib-parser
- [ ] Convert stylish-haskell API one by one to use ghc-lib-parser's data instead of it of current parser
- [ ] Remove source of and dependency on current parser

I am now trying to understand the source code related to current parser & how to use ghc-lib-parser, and add the dependency.

If the plan has problem, it is appreciated if you give me a hint.

Thank you.

**Comment by EncodePanda** [comment]
Closing this issue given our latest release 0.12.0.0 was mainly about that :)
