### ISSUE TITLE
Marked as broken on nixpkgs; add to Stackage?

### ISSUE THREAD

**Issue by rpearce** [jaspervdj/stylish-haskell#268]
Issue I opened on `nixpkgs`: https://github.com/NixOS/nixpkgs/issues/79130

[This comment](https://github.com/NixOS/nixpkgs/issues/79130#issuecomment-581360536) states that getting this published on Stackage would help this scenario.

(I also wonder if `hakyll`'s similar version issues in nixpkgs would be helped if it were published on Stackage?).

* * *

@jaspervdj Would you be interested in getting this published on Stackage?

**Comment by jaspervdj** [comment]
I'm interested in getting this on Stackage, I just don't really have time to do that myself right now.  Any assistance would be welcome.

I had a quick look at the original issue -- it seems like lowering the lower bound for `HsYAML` would also help.  We don't use much of `HsYAML` so that may be possible.

**Comment by rpearce** [comment]
I think it's a bit silly that `0.2.x` for `HsYAML` isn't be available on `nixpkgs`, and it feels wrong to me to ask you to change your package for that.

I've never published anything on Hackage – much less Stackage – but I'll look around, nonetheless, and try to lighten your load!

**Comment by rpearce** [comment]
Folks overrode it and should be fixed up: https://github.com/NixOS/nixpkgs/pull/79528

**Comment by jaspervdj** [comment]
Thanks for looking into this @rpearce!
