### ISSUE TITLE
HsYAML GPL license is probably not compatible with BSD

### ISSUE THREAD

**Issue by rtimush** [jaspervdj/stylish-haskell#277]
If my understanding is correct, GPL libraries, unfortunately, cannot be used in BSD-licensed applications. 

It's probably necessary to either switch back to `yaml`, or discuss if HsYAML can be re-licensed (personally, I would love to see the second as I also wanted to use HsYAML in my BSD-licensed tool).

**Comment by jaspervdj** [comment]
> If my understanding is correct, GPL libraries, unfortunately, cannot be used in BSD-licensed applications.

That is not correct.  In fact, if you are using GHC with libgmp, you probably already are using GPL-licensed code.

It is fine for a BSD3 application to depend on a GPL-licensed library. It does not affect the code of your tool, that code remains BSD3-licensed. However, if you distribute your tool as a binary, then that must adhere to the GPL license (which, again, is probably already the case if it's compiled with the standard GHC+libgmp).

In either case, if these conditions are not acceptable, I would definitely accept a PR that adds a flag to `stylish-haskell` which conditionally makes it use `yaml`.  But I think the default should be `HsYaml` since it doesn't depend on any C-libraries, which allows us to compile `stylish-haskell` with GHCJS etc.

**Comment by rtimush** [comment]
> if you are using GHC with libgmp, you probably already are using GPL-licensed code.

`libgmp` is LGPL/GPL, and as I understand it's LGPL that allows linking. For GPL it seems to not be the case, at least according to the [FSF FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL):

> **If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license?**
> Yes, because the program actually links to the library <...> the work as a whole must be licensed under the GPL.

Anyway, I'm not a lawyer, and I personally have nothing against stylish-haskell using HsYAML, so feel free to close the issue if you think it's not a problem.

**Comment by jaspervdj** [comment]
Oh, sorry, in that case I was wrong about libgmp.  Thanks for sorting that out.  In either case, I don't consider this a big problem but would be happy to accept a patch that adds `yaml` as an extra option.
