### ISSUE TITLE
Automatic removal (addition?) of LANGUAGE pragmas

### ISSUE THREAD

**Issue by meiersi** [jaspervdj/stylish-haskell#4]
For some extensions like `ViewPatterns` or `BangOperators` one can actually decide from the AST whether they are required or not. For other's like `FlexibleInstances` more effort is required.

It would be cool, if extensions whose necessity can be decided from the source code, would be removed automatically. This would alleviate the extension creep during the development of a project.

One could even think of automatically adding the extensions, as `haskell-src-exts` can determine for some whether they are required to parse the code or not.

**Comment by geraldus** [comment]
@jaspervdj hi!  I've faced an issue with automatic `ViewPattern` removal.  I have worked on `lamda-cms-core` code; `LambdaCms.Core.Foundation` won't compile without view patterns, but `stylish-haskell` removes it.

**Comment by jaspervdj** [comment]
@geraldus Could you link me to the file in question?

**Comment by geraldus** [comment]
@jaspervdj here it is https://github.com/lambdacms/lambdacms/blob/master/lambdacms-core/LambdaCms/Core/Foundation.hs

**Comment by jaspervdj** [comment]
@geraldus Looks like there are no `ViewPatterns` in the source, which is why `stylish-haskell` removes the pragma. However, the template Haskell call on line 65 generates code which uses `ViewPatterns`. There's not really a way `stylish-haskell` can detect that, so I would suggest changing `remove_redundant` to `false` for this project in a `stylish-haskell.yaml`.

**Comment by geraldus** [comment]
Thank you (:
